---
sidebar: sidebar 
permalink: concept-cvs-gcp.html 
keywords: cloud volumes service for gcp, google cloud, cloud volumes, cloud volumes service subscription 
summary: NetApp Cloud Volumes Service for Google Cloud を使用すると、マルチプロトコルワークロードを迅速に追加できるだけでなく、 Windows ベースと UNIX ベースの両方のアプリケーションを構築、導入することができます。 
---
= Cloud Volumes Service for Google Cloud の詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Cloud Volumes Service for Google Cloud を使用すると、マルチプロトコルワークロードを迅速に追加できるだけでなく、 Windows ベースと UNIX ベースの両方のアプリケーションを構築、導入することができます。



== 主な機能：

* オンプレミスと Google Cloud 間でデータを移行
* ボリュームを 1 から 100TiB に数秒でプロビジョニング
* マルチプロトコルのサポート（ NFS または SMB ボリュームを作成できます）
* 自動化された効率的なスナップショットでデータを保護します。
* 迅速なクローニングでアプリケーション開発を高速化




== コスト

Cloud Volumes Service for Google Cloudで作成されたボリュームは、BlueXPではなく、お客様のサブスクリプションに課金されます。

Cloud Volumes Service for Google CloudのリージョンまたはボリュームをBlueXPから検出する場合、料金は発生しません。

link:https://console.cloud.google.com/marketplace/product/endpoints/cloudvolumesgcp-api.netapp.com?q=cloud%20volumes%20service["Google Cloud Marketplace で価格を確認"^]



== サポートされている地域

https://cloud.netapp.com/cloud-volumes-global-regions#cvsGc["サポートされている Google Cloud リージョンを表示します。"^]



== 始める前に

BlueXPでは、既存のCloud Volumes Service for GCPサブスクリプションとボリュームを検出できます。を参照してください https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud のドキュメント"^] 月額プランをまだ設定していない場合は、



== サポートを受ける

BlueXPでのCloud Volumes Service の動作に関する一般的な質問は'BlueXPチャットを使用してください

Cloud Volumes Service for Google Cloud に関する一般的な質問については、ネットアップの Google Cloud チームに gcinfo@netapp.com まで E メールでお問い合わせください。

クラウドボリュームに関連する技術的な問題については、 Google Cloud Console を使用してテクニカルサポートケースを作成できます。を参照してください link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/support["サポートを受ける"^] を参照してください。



== 関連リンク

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["ネットアップのBlueXP：『Cloud Volumes Service for Google Cloud』"^]
* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud のドキュメント"^]

